package juego.enums;

public enum TipoCaracteristica
{
	PUNTOS_ACCION,
    PUNTOS_MOVIMIENTO,
    FUERZA,
    VITALIDAD,//11
    SABIDURIA,
    SUERTE,
    AGILIDAD,
    INTELIGENCIA,
    ALCANZE,
    CRIATURAS_INVOCABLES,
    DANOS_FIJOS,
    DANOS_FISICOS,
    DANOS_ARMAS,
    PORC_DANOS,
    CURACIONES,
    DANOS_TRAMPA,
    PORC_DANOS_TRAMPA,
    REENVIA_DANOS,
    GOLPES_CRITICOS,
    FALLOS_CRITICOS,
    ESQUIVA_PERD_PA,
    ESQUIVA_PERD_PM,
    RES_FIJA_NEUTRAL,
    RES_PORC_NEUTRAL,
    RES_FIJA_PVP_NEUTRAL,
    RES_PORC_PVP_NEUTRAL,
    RES_FIJA_TIERRA,//34
    RES_PORC_TIERRA,
    RES_FIJA_PVP_TIERRA,//36
    RES_PORC_PVP_TIERRA,
    RES_FIJA_AGUA,
    RES_PORC_AGUA,
    RES_FIJA_PVP_AGUA,//40
    RES_PORC_PVP_AGUA,
    RES_FIJA_AIRE,
    RES_PORC_AIRE,
    RES_FIJA_PVP_AIRE,//44
    RES_PORC_PVP_AIRE,
    RES_FIJA_FUEGO,
    RES_PORC_FUEGO,
    RES_FIJA_PVP_FUEGO,
    RES_PORC_PVP_FUEGO;
	
	public int get_Id() 
	{
        return ordinal() + 8;
    }
	
    public static TipoCaracteristica get_Id(int id)
    {
        return values()[id - 8];
    }
}
